//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.18 at 05:51:33 오후 KST 
//


package org.openflamingo.uploader.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for compressionMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="compressionMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LZO"/>
 *     &lt;enumeration value="GZIP"/>
 *     &lt;enumeration value="SNAPPY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "compressionMode")
@XmlEnum
public enum CompressionMode {

    LZO,
    GZIP,
    SNAPPY;

    public String value() {
        return name();
    }

    public static CompressionMode fromValue(String v) {
        return valueOf(v);
    }

}
