//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.17 at 11:46:47 오후 KST 
//


package org.openflamingo.uploader.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openflamingo.org/schema/uploader}sourceDirectory"/>
 *         &lt;element name="workingDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="completeDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="removeAfterCopy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="errorDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceDirectory",
    "workingDirectory",
    "completeDirectory",
    "removeAfterCopy",
    "errorDirectory"
})
@XmlRootElement(name = "local")
public class Local {

    @XmlElement(required = true)
    protected SourceDirectory sourceDirectory;
    @XmlElement(required = true)
    protected String workingDirectory;
    @XmlElement(required = true)
    protected String completeDirectory;
    @XmlElement(defaultValue = "false")
    protected boolean removeAfterCopy;
    @XmlElement(required = true)
    protected String errorDirectory;

    /**
     * Gets the value of the sourceDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDirectory }
     *     
     */
    public SourceDirectory getSourceDirectory() {
        return sourceDirectory;
    }

    /**
     * Sets the value of the sourceDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDirectory }
     *     
     */
    public void setSourceDirectory(SourceDirectory value) {
        this.sourceDirectory = value;
    }

    /**
     * Gets the value of the workingDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkingDirectory() {
        return workingDirectory;
    }

    /**
     * Sets the value of the workingDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkingDirectory(String value) {
        this.workingDirectory = value;
    }

    /**
     * Gets the value of the completeDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteDirectory() {
        return completeDirectory;
    }

    /**
     * Sets the value of the completeDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteDirectory(String value) {
        this.completeDirectory = value;
    }

    /**
     * Gets the value of the removeAfterCopy property.
     * 
     */
    public boolean isRemoveAfterCopy() {
        return removeAfterCopy;
    }

    /**
     * Sets the value of the removeAfterCopy property.
     * 
     */
    public void setRemoveAfterCopy(boolean value) {
        this.removeAfterCopy = value;
    }

    /**
     * Gets the value of the errorDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDirectory() {
        return errorDirectory;
    }

    /**
     * Sets the value of the errorDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDirectory(String value) {
        this.errorDirectory = value;
    }

}
